name: publish

on:
  push:
    tags:
      - '*'

permissions: {}

jobs:
  publish:
    runs-on: ubuntu-24.04
    permissions:
      contents: read # Required for actions/checkout
      id-token: write # Required for npm provenance/SLSA attestation ( --provenance flag )
      actions: read # For getting workflow run info to build provenance
    steps:
      - name: Checkout
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4.3.1
      - name: Setup Node.js
        uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4.4.0
        with:
          node-version-file: '.node-version'
          registry-url: 'https://registry.npmjs.org'
      - name: Install
        run: npm ci --ignore-scripts
      - name: Build
        run: npm run build:dist
      - name: Publish Package
        run: npm publish --access public --no-git-checks --provenance --tag ${{ github.sha }}
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
